### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-s1ftc#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Tomermk** [comment]
![image](https://user-images.githubusercontent.com/29456819/190514335-70a56614-af5b-4ab9-a98d-2b1f043ed07d.png)

**Comment by Tomermk** [comment]
![image](https://user-images.githubusercontent.com/29456819/190514425-a756bd7d-9043-4e46-abf7-56c84a1de40e.png)
